//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class DigitalMap
    {
        public int Id_Matr { get; set; }
        public byte[] Map { get; set; }
    
        public virtual SpacecraftInitialData SpacecraftInitialData { get; set; }
    }
}
