//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class NU
    {
        public int ID_NU { get; set; }
        public int N_NU { get; set; }
        public int Modification { get; set; }
        public double X { get; set; }
        public double Y { get; set; }
        public double Z { get; set; }
        public double VX { get; set; }
        public double VY { get; set; }
        public double VZ { get; set; }
        public double t { get; set; }
        public int Vitok { get; set; }
        public double Sbal { get; set; }
        public System.DateTime DateNU { get; set; }
        public string Comment { get; set; }
    
        public virtual SpacecraftInitialData SpacecraftInitialData { get; set; }
    }
}
