//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataBaseModel
{
    using System;
    using System.Collections.Generic;
    
    public partial class SpaceсraftCommonData
    {
        public int SpacecraftCommonDataId { get; set; }
        public int EngineId { get; set; }
    
        public virtual MassInertialCharacteristic MassInertialCharacteristic { get; set; }
        public virtual SpacecraftInitialData SpacecraftInitialData { get; set; }
    }
}
